name: CI

on: [push]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build DotNET40
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe /p:Configuration=Release $Env:GITHUB_WORKSPACE\HelloService

      - name: Setup Nuget.exe
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Build NuGet Package
        run: nuget pack HelloService\HelloService.nuspec -Version 1.0.0

      - name: Deploy Nuget Package
        run: |
          nuget setApiKey ${{ secrets.NUGET_DEPLOY_KEY }}
          nuget push *.nupkg -Source https://api.nuget.org/v3/index.json